config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: { minimum: 5, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article, foreign_key: 'article_id' 
  belongs_to :category, foreign_key: 'category_id'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates_uniqueness_of :name, on: :create, message: 'must be unique'
  validates :name, length: { minimum: 3, maximum: 20 }
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  has_many :articles, dependent: :destroy

  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }
  VALIDATE_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 100 },
                    format: { with: VALIDATE_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :require_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:alert] = "You must be logged in to perform action"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :require_user, except: %i[index show]
  before_action :require_same_user, only: %i[edit update destroy]
  after_action :previous_url, only: [:new]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.valid?
      @article.save
      flash[:notice] = 'Article was created succesfully.'
      Rails.logger.info('New article')
      redirect_to @article
    else
      render :new
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was succesfully updated!'
    else
      render action: 'edit'
    end
  end

  def destroy
    @article.destroy
    Rails.logger.info("Article #{@article.title} deleted")
    flash[:notice] = 'Article was succesfully destroyed!'
    redirect_to articles_path
  end

  private

  def set_article
    begin
      @article = Article.find(params[:id])
      Rails.logger.info "#{@article.inspect}"
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url, flash: { error: 'Article not found' }
    end
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = 'You can only edit or delete your own article'
      redirect_to @article
    end
  end

  def previous_url
    session[:return_to] ||= request.referer
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show update edit destroy]
  before_action :require_admin, except: %i[index edit show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.valid?
      @category.save
      flash[:notice] = 'Category was created!'
      redirect_to @category
    else
      render :new
    end
  end

  def show
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: "Category #{@category.name} was successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    unless logged_in? && current_user.admin?
      flash[:alert] = "Only admins can perform that action"
      redirect_to category_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

  def about; end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'Logged in succesfully'
      redirect_to user
    else
      flash.now[:alert] = 'There was something wrong with your login details'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update show destroy]
  before_action :require_user, only: %i[edit update]
  before_action :require_same_user, only: %i[edit update destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      flash[:notice] = "User #{@user.username} was succesfully signed up"
      Rails.logger.info("User #{@user.username} created")
      redirect_to @user
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User #{@user.username} was succesfully updated!"
    else
      render :edit
    end
  end

  def destroy 
    @user.destroy
    Rails.logger.info("Article #{@user.username} deleted")
    session[:user_id] = nil if @user == current_user
    flash[:notice] = 'Account and all associated articles deleted'
    redirect_to root
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = 'You can only edit or delete your profile'
      redirect_to current_user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'rounded shadow mx-auto d-block')
  end

  def flash_class(level)
    case level
    when 'notice' then 'alert-info'
    when 'success' then 'alert-success'
    when 'error' then 'alert-warning'
    when 'alert' then 'alert-danger'
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/articles/_article.html.erb
<div class="container">
  <%@articles.each do |article| %>
  <div class="row justify-content-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-body rounded">
        <div class="card-header fst-italic">
          <% if article.user %>
            by <%= link_to article.user.username, user_path(article.user) %>
          <% end %>
          <% if article.categories.any? %>
            <div class="mt-2"><%= render article.categories %></div>
          <% end %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article, class: "text-success" %></h5>
          <p class="card-text"><%= truncate(article.description, length: 100) %></p>
          <%= link_to "Read", article, class: "btn btn-outline-success" %>
          <% if logged_in? && (article.user == current_user || current_user.admin?) %>
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-primary" %>
            <%= button_to "Destroy", article, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
          edited <%= time_ago_in_words(article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded") do |f| %>

        <div class="form-group row mb-3">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row mb-3">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>

        <div class="form-group row mb-3">
          <%= f.label :category, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.collection_select(:category_ids, Category.all, :id, :name, { :prompt => "Empty" }, { :multiple => true, size: 3, class: "form-select shadow rounded" } )%>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg col-2"%>
        </div>

      <% end %>   
    </div>
    <div class="mb-3">
      <%= link_to "[ Cancel and return to articles listing ]", articles_path, class: "text-dark form-group row justify-content-center" %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Update Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'article' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-body rounded">
        <div class="card-header fst-italic">
          by <%= @article.user.username if @article.user %>
          <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
          <% if @article.categories.any? %>
            <div class="mt-2"><%= render @article.categories %></div>
          <% end %>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.description) %></div>
          <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-primary" %>
            <%= button_to "Delete", @article, method: :delete, confirm: 'Are you sure?', class: "btn btn-outline-danger" %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
          edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill bg-info m-1" %>

app/views/categories/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @category %>
      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded") do |f| %>

        <div class="form-group row mb-3">
          <%= f.label :name, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Category name" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg col-2" %>
        </div>

      <% end %>   
    </div>
    <div class="mb-3">
      <%= link_to "[ Cancel and return to categories listing ]", categories_path, class: "text-dark form-group row justify-content-center" %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category: <%= @category.name %></h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Listing all categories</h1>

<div class="container">
  <% @categories.each do |category| %>
  <div class="row justify-content-center">
    <div class="col-4 mt-4">
      <div class="card text-center shadow mb-5 bg-body rounded">
        <div class="card-body">
          <h5 class="card-title"><%= link_to category.name, category, class: "text-success" %></h5>
          <p class="card-text"><%= pluralize(category.articles.count, 'article') %></p>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(category.created_at) %> ago, 
          edited <%= time_ago_in_words(category.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %> </h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to 'Edit category name', edit_category_path(@category), class: 'btn btn-info'%>
  </div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render partial: 'articles/article' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Keallar", about_path, class: "text-white" %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg|%>
    <div class="alert <%= flash_class(name.to_s) %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>  
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          <li class="nav-item">
            <%= link_to "Bloggers", users_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Articles
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "View articles", articles_path, class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <% if logged_in? %>
                <li><%= link_to "Create new article", new_article_url, class: "dropdown-item" %></li>
              <% end %>
              <a class="dropdown-item" href="#">Something else here</a>
            </ul>
          </li>
           <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "View categories", categories_path, class: "dropdown-item" %></li>
              <% if logged_in? && current_user.admin? %>
                <li><%= link_to "Create new category", new_category_url, class: "dropdown-item" %></li>
              <% end %>
            </ul>
          </li>
          <% if logged_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= '(Admin)' if current_user.admin? %> Profile <%= current_user.username %>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %></li>
                <li><%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %></li>
                <li><%= button_to "Delete your profile", user_path(current_user), method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item text-danger" %></li>
              </ul>
            </li>
          <% end %>
        </ul>
        <div class="m-1">
        <% if logged_in? %> 
          <%= link_to current_user.username, user_path(current_user), class: "btn btn-outline-success btn-lg" %>
          <%= button_to "Logout", logout_path, class: "btn btn-outline-success btn-lg", method: :delete, role: "button", data: { confirm: 'Are you sure?' } %>
        <% else %>
          <%= link_to "Log in", login_path, class: "btn btn-outline-success btn-lg", role: "button" %>
          <%= link_to "Sign up", signup_path, class: "btn btn-success btn-lg", role: "button" %>
        <% end %>
        </div>
      </div>
    </div>
  </nav>

app/views/layouts/application.haml
= javascript_pack_tag 'application'
= stylesheet_pack_tag 'application'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>First</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", medila: 'all', "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %> 
  </head>

  <body class="d-flex flex-column">
    <%= render "layouts/navigation" %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>

<%= link_to "Back", :back %>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center text-black">
    <h1 class="display-4">Alpha Blog</h1>
    <p class="lead"></p>
    <hr class="my-4">
    <p></p>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded") do |u| %>

        <div class="form-group row mb-3">
          <%= u.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= u.text_field :username, class: "form-control shadow rounded", placeholder: "Enter your username" %>
          </div>
        </div>

        <div class="form-group row mb-3">
          <%= u.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= u.text_field :email, class: "form-control shadow rounded", placeholder: "Enter your email" %>
          </div>
        </div>

        <div class="form-group row mb-3">
          <%= u.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= u.password_field :password, class: "form-control shadow rounded", placeholder: "Enter your password" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= u.submit(@user.new_record? ? 'Sign up' : 'Update account', class: "btn btn-outline-light btn-lg col-2") %>
        </div>

      <% end %>   
    </div>
    <div class="mb-3">
      <%= link_to "[ Cancel and return to home page ]", root_path, class: "text-dark form-group row justify-content-center" %>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<div class="container">
  <%@users.each do |user| %>
  <div class="row justify-content-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-body rounded">
        <div class="card-header fst-italic">
          <%= link_to user.username, user %>
        </div>
        <div class="card-body">
          <%= link_to gravatar_for(user, size: 150), user %>
          <p class="card-text"><%= pluralize(user.articles.count, 'article') %></p>
          <%= link_to "Read", user, class: "btn btn-outline-success" %>
          <% if logged_in? %> 
            <% if user == current_user %>
              <%= link_to "Edit", edit_user_path(user), class: "btn btn-outline-primary" %>
            <% end %>
            <% if user.admin? && current_user.admin? %>
              <%= button_to 'Delete', user_path(user), method: :delete, data: {confirm: 'Are you sure?'} , class: "btn btn-outline-danger" %>
            <% end %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

<%= render 'user' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"> <%= @user.username %> </h1>

<%= gravatar_for @user, size: 200%>

<% if logged_in? && @user == current_user %>
  <div class="text-center mt-4">
    <%= link_to 'Edit category', edit_category_path(@category), class: "btn btn-primary"%>
  </div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render partial: 'articles/article' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>